Pbb34
CS275-Icebreaker/Icebreaker pull request #10
Opened 2018-03-06 16:38 UTC by pbb34

Updated views

2018-03-09 22:47 UTC, catvec requested changes
Good work so far. Only a minor issue with some image URLs. Other than that everything is ay-ok.

2018-03-09 22:47 UTC, Noah-Huppert commented on README.md
> +2. Install NPM components and create a package.json file inside Incebreaker project directory
Remove this change. `npm install` is the correct command.

2018-03-09 22:47 UTC, Noah-Huppert commented on src/www/assigned-topics.html
> +            <img src="img/sports.png">
Make all your urls absolute. Meaning they start with a slash.  

Ex: `/img/sports.png`.

2018-03-10 11:45 UTC, pbb34 commented
I’ll fix it boss

2018-03-10 21:13 UTC, Noah-Huppert commented
:ok_hand:

2018-03-13 02:34 UTC, pbb34 commented
Making URL's absolute was throwing errors such as "Unable to load the content" and images didn't load up. So keeping is same.

2018-03-13 14:02 UTC, closed without merging